const keywords: string[] = [
    "Mohammed Aydan",
    "Mohammed Aydan Portfolio",
    "محمد أيدن",
    "محمد أيدن سيرة ذاتية",
    "محمد أيدن بورتفوليو",
    "Mohammed Aydan Software Engineer",
    "Mohammed Aydan Developer",
    "Mohammed Aydan Full Stack Developer",
    "Mohammed Aydan Web Developer",
    "Mohammed Aydan GitHub",
    "Mohammed Aydan LinkedIn",
    "Mohammed Aydan Mansoura",
    "Mohammed Aydan Egypt",
    "Software Engineer",
    "Software Developer",
    "Web Developer",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Mobile App Developer",
    "Flutter Developer",
    "Dotnet Developer",
    "Dot net Core Developer",
    "Laravel Developer",
    "Next Developer",
    "Next.js Developer",
    "React Developer",
    "React.js Developer",
    "Portfolio",
    "Mohammed Aydan Portfolio",
    "محمد أيدن سيرة ذاتية",
    "سيرة ذاتية محمد أيدن",
    "مطور برمجيات",
    "مهندس برمجيات",
    "مطور ويب",
    "مبرمج مواقع",
    "مطور تطبيقات",
    "مطور تطبيقات موبايل",
    "مبرمج حر",
    "مبرمج فريلانسر",
    "مبرمج مستقل",
    "مبرمج ويب",
    "React.js",
    "Next.js",
    "Next.js 15",
    "JavaScript",
    "TypeScript",
    "HTML5",
    "CSS3",
    "Tailwind CSS",
    "Flutter",
    "Dart",
    "Laravel",
    "PHP",
    "MySQL",
    "PostgreSQL",
    ".NET Core",
    "C#",
    "REST API",
    "GraphQL",
    "Git",
    "GitHub",
    "Docker",
    "Firebase",
    "Supabase",
    "GetX",
    "Bloc",
    "Clean Architecture",
    "Responsive Design",
    "SEO",
    "Website Development",
    "Custom Web Application",
    "Mobile App Development",
    "Ecommerce Website",
    "Ecommerce Website Development",
    "Portfolio Website",
    "Blog Website",
    "Landing Page",
    "UI/UX Design",
    "تصميم مواقع",
    "برمجة مواقع",
    "برمجة تطبيقات",
    "برمجة تطبيقات موبايل",
    "تصميم واجهات",
    "تصميم تطبيقات",
    "تصميم تجربة المستخدم",
    "تحسين محركات البحث",
    "تطوير تطبيقات الجوال",
    "SEO Optimized Websites",
    "Fast Web Applications",
    "Responsive Web Design",
    "High Performance Websites",
    "مواقع متوافقة مع SEO",
    "تصميم مواقع متجاوبة",
    "مواقع سريعة التحميل",
    "Next.js SEO",
    "Server-side Rendering",
    "Static Site Generation",
    "Jamstack Developer",
    "Progressive Web Apps",
    "PWA Development",
    "Headless CMS",
    "Modern Web Development",
    "JavaScript Developer",
    "TypeScript Developer",
    "Frontend Engineering",
    "Backend Engineering",
    "Web Performance Optimization",
    "Software Consulting",
    "Tech Solutions",
    "App Development Services",
    "Web Application Design",
    "Cross-platform Development",
    "Cloud Integration",
    "API Development",
    "Microservices Architecture",
    "Scalable Applications",
    "Enterprise Software Development",
    "حلول تقنية",
    "خدمات تطوير التطبيقات",
    "تصميم تطبيقات متجاوبة",
    "تكامل سحابي",
    "تطوير واجهات برمجة التطبيقات",
    "برمجيات قابلة للتوسع",
    "تطوير برمجيات المؤسسات",
    "تطوير برمجيات التجارة الإلكترونية",
    "تطوير برمجيات الأمن",
    "تطوير برمجيات الإدارة",
    "تطوير برمجيات التعليم",
    "تطوير برمجيات الرعاية الصحية",
    "تطوير برمجيات الشركات",
    "تطوير برمجيات الصناعة",
    "تطوير برمجيات الخدمات",
    "تطوير برمجيات المال والأعمال",
    "تطوير برمجيات المدن",
    "تطوير برمجيات الملاحة",
    "تطوير برمجيات النقل",
    "تطوير برمجيات الأمن السيبراني",
    "تطوير برمجيات البيانات الضخمة",
    "تطوير برمجيات الذكاء الاصطناعي",
    "تطوير برمجيات الشبكات",
    "تطوير برمجيات المضادات الحيوية",
    "تطوير برمجيات الأجهزة",
    "تطوير برمجيات المعدات",
    "تطوير برمجيات المخازن",
    "تطوير برمجيات المخازن الضخمة",
    "تطوير برمجيات المخازن السحابية",
    "تطوير برمجيات المخازن الأمنية"
];

export default keywords;
