const keywords: string[] = [
  // Personal Branding
  "Mohammed Aydan",
  "محمد أيدن",
  "Mohammed Aydan Software Engineer",
  "Mohammed Aydan Full Stack Developer",
  "Mohammed Aydan Portfolio",
  "محمد أيدن بورتفوليو",
  "Mohammed Aydan Egypt",
  "Mohammed Aydan Mansoura",
  "محمد أيدن مطور برمجيات",
  "محمد أيدن سيرة ذاتية",

  // Roles and Expertise
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Mobile App Developer",
  "Flutter Developer",
  "Next.js Developer",
  "React.js Developer",
  ".NET Core Developer",
  "Laravel Developer",
  "Software Engineer",
  "Web Developer",
  "مطور ويب",
  "مهندس برمجيات",
  "مطور تطبيقات موبايل",
  "مبرمج مستقل",

  // Technologies
  "Next.js",
  "React.js",
  "Flutter",
  ".NET Core",
  "Laravel",
  "Firebase",
  "Supabase",
  "MySQL",
  "JavaScript",
  "TypeScript",
  "Tailwind CSS",
  "C#",
  "PHP",
  "REST API",
  "GraphQL",
  "Git",
  "Docker",
  "Clean Architecture",

  // Services and Specializations
  "Web Development",
  "Mobile App Development",
  "Ecommerce Website Development",
  "Portfolio Website",
  "Blog Website",
  "Responsive Web Design",
  "SEO Optimized Websites",
  "Next.js SEO",
  "Server-side Rendering",
  "Static Site Generation",
  "Progressive Web Apps",
  "Headless CMS",
  "API Development",
  "Cloud Integration",
  "Microservices Architecture",
  "Scalable Web Applications",
  "UI/UX Design",
  "تصميم مواقع متجاوبة",
  "تحسين محركات البحث",
  "تطوير تطبيقات الجوال",
  "تطوير واجهات برمجة التطبيقات",
  "تصميم واجهات المستخدم",
  "تطوير مواقع التجارة الإلكترونية",

  // Location-Based
  "Web Developer Egypt",
  "Full Stack Developer Egypt",
  "Flutter Developer Egypt",
  "Next.js Developer Egypt",
  "Software Engineer Mansoura",
  "مطور برمجيات مصر",
  "مطور ويب المنصورة",
];

export default keywords;